name: "Exportar a Itch.io"
on:
  push:
    branches:
      - main 

jobs:
  export_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Exportar para Web
        uses: firebelley/godot-export@v5.2.1
        with:
          # URLs directas desde los servidores de versiones de Godot
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Publicar en Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: rafax20/tablero-didactico
          ITCH_USER: rafax20       
          PACKAGE: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/web.zip